----------------- REPORT 1  ----------------------

SELECT  LA.PAIS  FROM(
SELECT  DISTINCT T1.PAIS, COUNT(T1.ID_USER) AS REPRO   FROM
(SELECT  US.ID_USER, US.PAIS,RE.MUSICA  FROM USUARIO US INNER JOIN REPRODUCCION RE  ON  US.ID_USER = RE.USERID) T1
GROUP BY T1.PAIS ORDER BY REPRO DESC ) LA  WHERE ROWNUM <= 5 ; 


-------------- REPORT 2 -------------------------
SELECT  LA.GENERO  FROM(
SELECT DISTINCT T1.GENERO, COUNT(T1.GENERO) AS GENDER  FROM(
SELECT  SON.NOMBRE,SON.ARTISTA,SON.GENERO,RE.MUSICA  FROM CANCION SON INNER JOIN REPRODUCCION RE  ON  SON.IDCANCION = RE.MUSICA AND SON.GENERO IS NOT NULL ) T1
GROUP BY T1.GENERO   ORDER BY  GENDER DESC) LA WHERE ROWNUM<=5;

-------------- REPORTE 3 ------------------------

SELECT  DISTINCT T1.PAIS   FROM (SELECT  US.PAIS,RE.MUSICA,CA.GENERO  FROM USUARIO US INNER JOIN REPRODUCCION RE  ON  US.ID_USER = RE.USERID 
INNER JOIN CANCION CA ON RE.MUSICA = CA.IDCANCION ) T1
WHERE  T1.GENERO = 'Pop' ;


------------ REPORTE 4 --------------------------


SELECT        PAIS, ARTISTA, REPRO
FROM            (SELECT DISTINCT PAIS, ARTISTA, COUNT(NOMBRE) AS REPRO
                          FROM            (SELECT        CA.NOMBRE, CA.ARTISTA, RE.USERID, US.PAIS
                                                    FROM            CANCION CA, REPRODUCCION RE, USUARIO US
                                                    WHERE        CA.IDCANCION = RE.MUSICA AND RE.USERID = US.ID_USER ) T1
                          GROUP BY PAIS, ARTISTA) T2
WHERE        (REPRO >= 1)  AND   ARTISTA = 'Ace of Base'
ORDER BY REPRO  




------------ REPORTE 5 --------------------------

SELECT        ARTISTA, REPRO,USERID
FROM            (SELECT DISTINCT ARTISTA, COUNT(NOMBRE) AS REPRO, USERID
                          FROM            (SELECT        CA.NOMBRE, CA.ARTISTA, RE.USERID, US.PAIS
                                                    FROM            CANCION CA, REPRODUCCION RE, USUARIO US
                                                    WHERE        CA.IDCANCION = RE.MUSICA AND RE.USERID = US.ID_USER) T1
                          GROUP BY ARTISTA, USERID) T2
WHERE        (REPRO >= 1) AND  USERID = 'USUARIO1'
ORDER BY REPRO

