CREATE TABLE ARTISTA
(
NOMBRE VARCHAR2(40) PRIMARY KEY NOT NULL,
PAIS VARCHAR2(20),
AÑOS VARCHAR2(10)
);

CREATE TABLE ALBUM
(
IDAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(40) ,
ARTIST VARCHAR2(20),
AÑOS VARCHAR2(10),
FOREIGN KEY (ARTIST) REFERENCES ARTISTA(NOMBRE)
);



CREATE TABLE CANCION 
(
IDCANCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(200),
ARTISTA VARCHAR2(60),
ALBUM VARCHAR2(50),
AÑO_PUB INT,
GENERO VARCHAR2(20),
DURACION VARCHAR2(5),
LYRICS VARCHAR2(4000),
RATING VARCHAR2(1),
FOREIGN KEY (ARTISTA) REFERENCES ARTISTA(NOMBRE)
);

CREATE TABLE USUARIO 
(
ID_USER VARCHAR2(20) PRIMARY KEY NOT NULL,
PASS VARCHAR2(20),
NOMBRE VARCHAR2(50),
BIRTH DATE,
PAIS VARCHAR2(10),
MAIL VARCHAR2(50)
);

CREATE TABLE REPRODUCION
(
IDEN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
USERID VARCHAR2(20),
MUSICA INT,
FECHA DATE,
HORA DATE,
FOREIGN KEY (USERID) REFERENCES USERS(ID_USER),
FOREIGN KEY (MUSICA) REFERENCES CANCION(IDCANCION)
);

CREATE TABLE SONGCOL
(
IDSC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
IDCANCION INT ,
COLABORADOR VARCHAR2(20),
FOREIGN KEY (IDCANCION) REFERENCES CANCION(IDCANCION)
);

CREATE TABLE CANCIONTEMP 
(
IDCANCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
ARTISTA VARCHAR2(105),
NOMBRE VARCHAR2(300),
ALBUM VARCHAR2(100),
ANO_PUB INT,
GENERO VARCHAR2(20),
DURACION VARCHAR2(5)
);

select count(*) from CANCIONTEMP;



INSERT INTO REPRODUCCION (USERID, MUSICA,HORA,FECHA)  values ('USUARIO1',4,  to_char(sysdate,'HH:MI:SS'), to_char(sysdate,'DD/MM/YYYY') );



   
 



select to_char(sysdate,'HH:MI:SS') from dual;
select to_char(sysdate,'DD/MM/YYYY') from dual;
    
