
-------------  USERS ADMINISTRATOR -------------------

CREATE LOGIN ADMINISTRATOR WITH PASSWORD = 'ROOT';
USE DB_PRACTICA2
CREATE USER ADMINS FOR LOGIN ADMINISTRATOR
GO

GRANT SELECT,INSERT,DELETE,UPDATE ON ALUNO TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON AREA TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON CONFIGURACION TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON CURSO TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON CURSO_FACU_AREA TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON FACULDADE TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON HORARIO TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON PRE_POST TO ADMINS
GRANT SELECT,INSERT,DELETE,UPDATE ON PROFESSOR TO ADMINS
GO

GRANT EXECUTE ON ADDAREA TO ADMINS
GRANT EXECUTE ON ADDFACU TO ADMINS
GRANT EXECUTE ON ADDCOURSE TO ADMINS
GRANT EXECUTE ON ADDUSER TO ADMINS
GRANT EXECUTE ON ADDWORKER TO ADMINS
GRANT EXECUTE ON ADDSPH TO ADMINS
GRANT EXECUTE ON EDITSTATUS TO ADMINS
GO

-------------USER ESTUDIANTE ----------------

CREATE LOGIN ESTUDIANTE WITH PASSWORD = 'STDNT';
USE DB_PRACTICA2
CREATE USER ALUNO FOR LOGIN ESTUDIANTE
GO

GRANT SELECT,INSERT,DELETE ON ASIGNACION TO ALUNO
GRANT SELECT ON CURSO TO ALUNO
GRANT SELECT ON HORARIO TO ALUNO
GRANT SELECT ON CURSO_FACU_AREA TO ALUNO

GRANT EXECUTE ON VIEWCOURSES TO ALUNO
GRANT EXECUTE ON ASIGCOURSE TO ALUNO
GRANT EXECUTE ON VIEWXML TO ALUNO
GO

-------------USER ESTUDIANTE ----------------

CREATE LOGIN DOCENTE WITH PASSWORD = 'DCNT';
USE DB_PRACTICA2
CREATE USER PROFE FOR LOGIN DOCENTE
GO

GRANT UPDATE,SELECT ON ASIGNACION TO PROFE
GRANT SELECT ON CURSO TO PROFE
GRANT SELECT ON HORARIO TO PROFE
GRANT EXECUTE ON UPDATENOTES TO PROFE

GO
