

    Use [master]
    go

    CREATE DATABASE DB_PRACTICA2 ON  PRIMARY 
    ( NAME = N'DB_PRACTICA2', 
      FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DB_PRACTICA2.mdf', 
      SIZE = 70656KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1014KB)
     LOG ON 
    ( NAME = N'DB_PRACTICA2_log', 
      FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DB_PRACTICA2_log.ldf', 
      SIZE = 164671KB , MAXSIZE = 1048GB , FILEGROWTH = 10%)
    GO


USE DB_PRACTICA2;
GO 

/*****  CREATE TABLES **********/

CREATE TABLE ALUNO 
(
CARNE INT PRIMARY KEY NOT NULL, 
NOMBRE VARCHAR(50), 
CELULAR INT,
BIRTH DATE,
TELEFONO INT,
DIR VARCHAR(20),
MAIL VARCHAR(30),
CARRERA INT
);

CREATE TABLE PROFESSOR
(
ID_PROF INT PRIMARY KEY NOT NULL, 
NOMBRE VARCHAR(50), 
CELULAR INT,
BIRTH DATE,
TELEFONO INT,
DIR VARCHAR(20),
MAIL VARCHAR(30),
CARRERA INT
);


CREATE TABLE AREA 
(
ID_AREA INT PRIMARY KEY NOT NULL, 
NOMBRE VARCHAR(20) 
);

CREATE TABLE FACULDADE
(
ID_FAC INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20)
);




CREATE TABLE CURSO 
(
ID_CURSO INT PRIMARY KEY NOT NULL ,
NOMBRE VARCHAR(30),
SEMESTRE INT,
CREDITOS INT,
STAT INT
);

CREATE TABLE PRE_POST
(
IDPP INT IDENTITY(1,1) PRIMARY KEY,
ID_CURSO INT NOT NULL,
ID_FAC INT NOT NULL,
PRE VARCHAR(50),
POST VARCHAR(50),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
FOREIGN KEY (ID_FAC) REFERENCES FACULDADE(ID_FAC)
);

CREATE TABLE CURSO_FACU_AREA
(
IDCAF INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
ID_CURSO INT NOT NULL,
ID_FAC INT NOT NULL, 
ID_AREA INT NOT NULL,
FOREIGN KEY (ID_AREA) REFERENCES AREA (ID_AREA),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
FOREIGN KEY (ID_FAC) REFERENCES FACULDADE(ID_FAC) 
);


CREATE TABLE HORARIO
(
ID_HORARIO INT IDENTITY(1,1) PRIMARY KEY ,
ID_CURSO INT NOT NULL,
HORA VARCHAR(15) NOT NULL,
DIA VARCHAR(10) NOT NULL,
SALON INT NOT NULL,
ID_CATE INT NOT NULL
FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO),
FOREIGN KEY (ID_CATE) REFERENCES PROFESSOR (ID_PROF)
);

CREATE TABLE ASIGNACION
(
ID_ASIGNACAO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ID_EST INT NOT NULL,
ID_HORAR INT,
SEMESTRE INT,
AÑO INT,
ZONA INT,
FINAL INT,
FOREIGN KEY (ID_EST) REFERENCES ALUNO (CARNE),
FOREIGN KEY (ID_HORAR) REFERENCES HORARIO (ID_HORARIO)

);


CREATE TABLE CONFIGURACION
(
AÑO INT NOT NULL,
SEMESTRE INT NOT NULL
);






