OPTIONS (SKIP=2)
LOAD DATA  
INFILE 'C:\Users\Public\Documents\CANCIONES.csv' 
INTO TABLE CANCION REPLACE FIELDS TERMINATED BY ',' optionally enclosed by '"' TRAILING NULLCOLS
(ARTISTA,NOMBRE,ALBUM,ANO_PUB,GENERO,DURACION)