OPTIONS (SKIP=2)
LOAD DATA  
INFILE 'C:\Users\Public\Documents\USERS.csv' 
INTO TABLE USUARIO REPLACE FIELDS TERMINATED BY ',' 
(
ID_USER,
PASS,
NOMBRE,
BIRTH "TO_DATE(:BIRTH, 'DD-MON-YYYY', 'NLS_DATE_LANGUAGE=ENGLISH')",
PAIS,
MAIL
)