----------MY SQL----------

CREATE DATABASE EDUCANDO;
USE EDUCANDO;

CREATE TABLE ITEM
(
 ID_ITEM  INT PRIMARY KEY NOT NULL,
 NOMBRE VARCHAR(20),
 TIPO VARCHAR(10),
 UNITVALUE float
);

ALTER TABLE ITEM ADD  UNIDADM INT ;
CREATE TABLE CENTROCOSTO
(
IDCC INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20),
RUBRO INT
);


CREATE TABLE EMPLEADO
(
DPI INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
PUESTO VARCHAR(10),
CC INT,
FOREIGN KEY(CC) REFERENCES CENTROCOSTO(IDCC)

);

CREATE TABLE SOLICITUD
(
IDSOL INT PRIMARY KEY NOT NULL,
FECHA DATE , 
RESPONSABLE INT ,
CANTIDAD INT,
TOTAL FLOAT,
FOREIGN KEY(RESPONSABLE) REFERENCES EMPLEADO(DPI)
);


CREATE TABLE SOL_ITEM
(
IDSO INT ,
IDITEM INT,
VALTOT INT,
FOREIGN KEY (IDSO) REFERENCES SOLICITUD(IDSOL),
FOREIGN KEY (IDITEM) REFERENCES ITEM (ID_ITEM)
);

CREATE TABLE PROVEEDOR
(
NIT INT PRIMARY KEY ,
NOMBRE VARCHAR(50)
);

CREATE TABLE COTIZACION 
(
IDCOT INT PRIMARY KEY NOT NULL,
IDSOL INT ,
FECHA DATE,
IDPRO INT,
FOREIGN KEY (IDSOL) REFERENCES SOLICITUD (IDSOL),
FOREIGN KEY (IDPRO) REFERENCES PROVEEDOR (NIT)
);

CREATE TABLE ORDENC
(
IDORDEN INT PRIMARY KEY NOT NULL,
FECHAENTREGA DATE,
IDCO INT,
CANTDES INT,
CANTSOL INT,
MONTO FLOAT,
FOREIGN KEY(IDCO) REFERENCES COTIZACION(IDCOT)
);

------------------ ALMACEN---------------------

CREATE TABLE FACTURA
(
FACTURA INT PRIMARY KEY,
FECHA DATE,
TOTAL FLOAT,
IDPRO INT,
FOREIGN KEY (IDPRO) REFERENCES PROVEEDOR(NIT)
);

CREATE TABLE FACT_DETALHE
(
 CANT INT ,
 IDFAC INT ,
 IITEM INT,
 FOREIGN KEY (IITEM) REFERENCES ITEM(ID_ITEM)
);

CREATE TABLE INCOMING
(
IDCOM INT PRIMARY KEY,
FECHA DATE,
TOTGOODS INT , 
VALTOT FLOAT,
PROVE INT,
FACTUR INT ,
FOREIGN KEY (FACTUR) REFERENCES FACTURA(FACTURA),
FOREIGN KEY (PROVE) REFERENCES PROVEEDOR(NIT)
);

CREATE TABLE DETALHE_INCOMING
(
CANT INT,
IDCO INT,
ITEM INT,
FOREIGN KEY (IDCO) REFERENCES INCOMING(IDCOM),
FOREIGN KEY (ITEM) REFERENCES ITEM(ID_ITEM)
);



CREATE TABLE GOODELIVERED
(
IDSAL INT PRIMARY KEY NOT NULL,
FECHASAL DATE,
FECHAENTREGA DATE,
DIRECCION VARCHAR(50),
IDEMPR INT,
FOREIGN KEY(IDEMPR) REFERENCES EMPLEADO(DPI)
);

CREATE TABLE DETALHE_DELIVERED
(
CANT INT,
IDSA INT ,
ITEMS INT ,
FOREIGN KEY(IDSA) REFERENCES GOODELIVERED(IDSAL),
FOREIGN KEY(ITEMS) REFERENCES ITEM(ID_ITEM)
);







