-----------ORACLE----------


CREATE TABLE AEROPUERTO
(
ID_AERO int primary KEY NOT NULL,
NOMBRE varchar(50),
CIUDAD VARCHAR(50),
PAIS varchar(50),
ATERRIZAJE varchar(20),
DESPLIEGUE varchar(20)

);

CREATE TABLE AVION(
ID_AVION int primary key not null,
MODELO varchar(20),
CAPACIDAD int
);

CREATE TABLE AERO_PLANE 
(
ID_AERO int not null,
ID_AVION int not null,
FOREIGN KEY (ID_AERO) REFERENCES AEROPUERTO(ID_AERO),
FOREIGN KEY (ID_AVION) REFERENCES AVION(ID_AVION)
);


CREATE TABLE PROGRAMAS (
ID_PROGRAMA int primary key not null,
LINEA varchar(20),
LUGAR_DESPEGUE varchar(50),
LUGAR_ATERRIZAJE varchar(50),
DIAS Array,
ID_AERO int,
FOREIGN KEY (ID_AERO) REFERENCES AEROPUERTO(ID_AERO)

);

CREATE TABLE VUELO 
(
ID_VUELO INT primary key,
FECHA date,
PLAZA_VACIA int,
ID_PROGRAMA int, 
FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMAS(ID_PROGRAMA)
);

CREATE TABLE ESCALA
(
ID_ESORDEN int primary key, 
NO_ESCALA int , 
LUGAR varchar(50),
ID_VUE int,
FOREIGN KEY (ID_VUE) REFERENCES VUELO(ID_VUELO)
);

